#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { transformSync } from '@babel/core';
import presetReact from '@babel/preset-react';
import { buildSync } from 'esbuild';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const checkOnly = process.argv.includes('--check');
const vendorOutputPath = path.join(root, 'ui_kits', 'shared', 'react-vendor.js');

const sharedFiles = [
  'ui_kits/shared/DataCoverage.jsx',
  'ui_kits/shared/TrustBadge.jsx',
  'ui_kits/shared/ShippingVisibility.jsx',
  'ui_kits/shared/Header.jsx',
  'ui_kits/shared/MetricCard.jsx',
  'ui_kits/shared/ChartCard.jsx',
  'ui_kits/shared/InsightFeed.jsx',
  'ui_kits/shared/Footer.jsx',
];

const dashboards = [
  'national-status-dashboard',
  'fuel-security-dashboard',
  'australian-fuel-strategy-dashboard',
  'qld-fuel-sovereignty-dashboard',
  'resource-value-dashboard',
  'state-contribution-dashboard',
  'strategic-resources-dashboard',
  'defence-alliances-dashboard',
  'defence-procurement-watch',
  'fuel-dashboard',
  'fertilizer-dashboard',
  'oil-and-production',
  'who-pays-what',
  'au-economics-dashboard',
  'housing-economic-pressure-dashboard',
  'manufacturing-dashboard',
  'power-grid-dashboard',
  'infrastructure-dashboard',
  'brisbane-2032-readiness-dashboard',
  'employment-automation-dashboard',
  'missing-data-scoreboard',
];

function normalizeNewlines(text) {
  return text.replace(/\r\n/g, '\n');
}

function read(relPath) {
  return fs.readFileSync(path.join(root, relPath), 'utf8');
}

function writeOrCheck(outputPath, output) {
  if (checkOnly) {
    const existing = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, 'utf8') : null;
    if (existing === null || normalizeNewlines(existing) !== normalizeNewlines(output)) {
      throw new Error(`${path.relative(root, outputPath)} is missing or stale. Run npm run build:ui.`);
    }
    return;
  }
  fs.writeFileSync(outputPath, output, 'utf8');
  console.log(`Wrote ${path.relative(root, outputPath)}`);
}

function buildReactVendor() {
  const result = buildSync({
    stdin: {
      contents: [
        "import React from 'react';",
        "import { createRoot } from 'react-dom/client';",
        'Object.assign(globalThis, { React, ReactDOM: { createRoot } });',
      ].join('\n'),
      loader: 'js',
      resolveDir: root,
      sourcefile: 'react-vendor-entry.js',
    },
    bundle: true,
    define: { 'process.env.NODE_ENV': '"production"' },
    format: 'iife',
    legalComments: 'none',
    minify: true,
    platform: 'browser',
    target: ['es2020'],
    treeShaking: true,
    write: false,
  });
  const code = result.outputFiles?.[0]?.text;
  if (!code) throw new Error('esbuild produced no React vendor output');
  const output = [
    '// Generated by scripts/build_ui.mjs from package-lock-controlled React dependencies.',
    '// Do not edit by hand. Run npm run build:ui.',
    code.trimEnd(),
    '',
  ].join('\n');
  writeOrCheck(vendorOutputPath, output);
}

function validateDashboardRuntime(name) {
  const html = read(`ui_kits/${name}/index.html`);
  if (/https?:\/\/[^"']+(?:react|react-dom)/i.test(html)) {
    throw new Error(`ui_kits/${name}/index.html loads an external React runtime`);
  }
  if (!html.includes('../shared/react-vendor.js')) {
    throw new Error(`ui_kits/${name}/index.html does not load the local React production bundle`);
  }
}

function compileDashboard(name) {
  const sourcePath = path.join(root, 'ui_kits', name, 'app.jsx');
  const outputPath = path.join(root, 'ui_kits', name, 'app.compiled.js');
  const sources = [
    ...sharedFiles.map(file => `// ${file}\n${read(file)}`),
    `// ui_kits/${name}/app.jsx\n${fs.readFileSync(sourcePath, 'utf8')}`,
  ];
  const source = sources.join('\n\n');
  const result = transformSync(source, {
    babelrc: false,
    configFile: false,
    comments: false,
    compact: false,
    presets: [[presetReact, { runtime: 'classic' }]],
    sourceType: 'script',
  });
  if (!result?.code) {
    throw new Error(`Babel produced no output for ${name}`);
  }
  const output = [
    '// Generated by scripts/build_ui.mjs. Do not edit by hand.',
    '// Edit the page app.jsx source or shared JSX components, then run npm run build:ui.',
    result.code,
    '',
  ].join('\n');

  writeOrCheck(outputPath, output);
}

buildReactVendor();
for (const dashboard of dashboards) {
  validateDashboardRuntime(dashboard);
  compileDashboard(dashboard);
}
